- label: "Preview"
  message: "PR $prNumber"
  color: "blue"
  url: "https://github.com/Streamer-bot-Extensions/Streamer.bot-Extensions-Wiki/pull/$prNumber"
   
- label: "Author"
  message: "$payload.pull_request.user.login"
  color: "green"
   
- label: "Localized"
  color: "green"
  imageUrl: "https://badges.crowdin.net/streamer-bot-extensions-wiki/localized.svg"
  url: "https://translate.botextensions.dev/project/streamer-bot-extensions-wiki"
  
- label: "Changelog CI"
  color: "green"
  imageUrl: "https://github.com/Streamer-bot-Extensions/Streamer.bot-Extensions-Wiki/actions/workflows/changelog-ci.yml/badge.svg"

- label: "JIRA"
  message: "$issuePrefix"
  color: "blue"
  url: "https://jira.company.com/browse/$issuePrefix"
  when: "$issuePrefix"

- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 500"

- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions > 200 && $additions < 500"

- label: "Label"
  message: "Feature"
  when: "$labels.includes('Feature')"

- label: "Description length"
  message: "$payload.pull_request.body.length"
  color: "green"
