changelog_type: 'pull_request'
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: true
include_unlabeled_changes: true
unlabeled_group_title: 'Unlabeled Changes'
pull_request_title_regex: '.*'
version_regex: '.*'
group_config:
  - title: Added
    labels:
      - extensions
      - overlays
      - tutorials
  - title: Updates
    labels:
      - update
