files:
  - source: /
    ignore:
      - /de/
      - /es/
      - /fr/
      - /pt-br/
      - /logos/
      - /.github/
      - '*.png'
      - '*.zip'
      - '*.rar'
      - '*.gif'
      - '*.json'
      - '*.dll'
      - '*.webm'
      - '*.toml'
      - '*.yml'
      - '*.yaml'
      - '.gitignore'
    translation: /%two_letters_code%/%original_file_name%
